---
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a VPC with web application
Parameters:
  VPCName:
    Description: Name for the VPC
    Type: String
    Default: vpc-web
  SSHLocation:
    Description: Source IP address range that can be used for SSH
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  KeyName:
    Description: Existing SSH key name for EC2 instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Mappings:
  SubnetConfig:
    VPC:
      CIDR: "10.0.0.0/16"
    Public0:
      CIDR: "10.0.0.0/24"
    Public1:
      CIDR: "10.0.1.0/24"
    Private0:
      CIDR: "10.1.0.0/24"
    Private1:
      CIDR: "10.1.1.0/24"

  AZRegions:
    sa-east-1:
      AZs: ["a", "c"]

Resources:

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      CidrBlock:
        Fn::FindInMap:
          - "SubnetConfig"
          - "VPC"
          - "CIDR"
      Tags:
        -
          Key: "Application"
          Value:
            Ref: "AWS::StackName"
        -
          Key: "Name"
          Value: !Ref 'VPCName'

  PublicSubnet0:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId:
        Ref: "VPC"
      AvailabilityZone:
        Fn::Sub:
          - "${AWS::Region}${AZ}"
          - AZ: !Select [ 0, !FindInMap [ "AZRegions", !Ref "AWS::Region", "AZs" ] ]
      CidrBlock:
        Fn::FindInMap:
          - "SubnetConfig"
          - "Public0"
          - "CIDR"
      MapPublicIpOnLaunch: "true"
      Tags:
        -
          Key: "Application"
          Value:
            Ref: "AWS::StackName"
        -
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-public-'
              - !Select [ 0, !FindInMap [ "AZRegions", !Ref "AWS::Region", "AZs" ] ]

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        -
          Key: "Application"
          Value:
            Ref: "AWS::StackName"
        -
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-IGW'

  AttachIGWToVPC:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId:
        Ref: "VPC"
      InternetGatewayId:
        Ref: "InternetGateway"

  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: "VPC"
      Tags:
        -
          Key: "Application"
          Value:
            Ref: "AWS::StackName"
        -
          Key: "Name"
          Value: !Join
            - ''
            - - !Ref "VPCName"
              - '-public-route-table'

  PublicRoute:
    Type: "AWS::EC2::Route"
    DependsOn: "AttachIGWToVPC"
    Properties:
      RouteTableId:
        Ref: "PublicRouteTable"
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId:
        Ref: "InternetGateway"

  PublicSubnetRouteTableAssociation0:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId:
        Ref: "PublicSubnet0"
      RouteTableId:
        Ref: "PublicRouteTable"

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join
        - '-'
        - - !Ref "VPCName"
          - WebSecurityGroup
      VpcId: !Ref VPC
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref 'SSHLocation'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: '0.0.0.0/0'
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: '0.0.0.0/0'
      Tags:
        -
          Key: Name
          Value: !Join
            - '-'
            - - !Ref "VPCName"
              - WebSecurityGroup

  Eth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: eth0
      GroupSet: [!Ref 'WebSecurityGroup']
      SubnetId: !Ref PublicSubnet0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-058943e7d9b9cabfb
      InstanceType: t3.micro
      KeyName: !Ref 'KeyName'
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref 'Eth0'
        DeviceIndex: '0'
      Tags:
      - Key: Name
        Value: instance-web
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            # userdata script - begin

            APP_URL=https://github.com/udhos/gowebhello/releases/download/v0.7/gowebhello_linux_amd64

            echo >&2 "env var APP_URL=[$APP_URL]"

            if [ -z "$APP_URL" ]; then
                  echo >&2 "missing env var APP_URL=[$APP_URL]"
                  exit 1
            fi

            app_dir=/web

            [ -d $app_dir ] || mkdir $app_dir
            cd $app_dir || echo >&2 "could not cd: app_dir=$app_dir"

            [ -f gowebhello ] || curl -L -o gowebhello "$APP_URL"

            chmod a+rx gowebhello

            #
            # web service
            #

            cat >/lib/systemd/system/web.service <<__EOF__
            [Unit]
            Description=Gowebhello Service
            After=network.target

            [Service]
            Type=simple
            User=root
            WorkingDirectory=$app_dir
            ExecStart=$app_dir/gowebhello
            Restart=on-failure

            [Install]
            WantedBy=multi-user.target
            __EOF__

            #
            # healthcheck script
            #

            cat >$app_dir/healthcheck.sh <<'__EOF__' ;# caution: quotes force full here-doc as literal
            #!/bin/bash

            url=http://localhost:8080/www/

            while :; do
                    sleep 5
                    http_code=$(curl -o /dev/null -s -I -X GET -w '%{http_code}' "$url")
                    exit_status=$?
                    echo >&2 "exit_status=$exit_status http_code=$http_code"
                    if [ "$exit_status" -ne 0 ] || [ "$http_code" != 200 ]; then
                          echo >&2 restarting: systemctl restart web.service
                          systemctl restart web.service
                    fi
            done
            __EOF__

            chmod a+rx $app_dir/healthcheck.sh

            #
            # healthcheck service
            #

            cat >/lib/systemd/system/healthcheck.service <<__EOF__
            #!/bin/bash

            [Unit]
            Description=Health Check Service
            After=network.target

            [Service]
            Type=simple
            User=root
            WorkingDirectory=$app_dir
            ExecStart=$app_dir/healthcheck.sh
            Restart=on-failure

            [Install]
            WantedBy=multi-user.target
            __EOF__

            systemctl daemon-reload
            systemctl enable web.service
            systemctl restart web.service
            systemctl enable healthcheck.service
            systemctl restart healthcheck.service

            echo "check service: systemctl status web healthcheck"
            echo "check logs:    journalctl -u web -u healthcheck -f"
            # userdata script - end

Outputs:

  VPCId:
    Description: "VPCId of VPC"
    Value:
      Ref: "VPC"
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-VPC"

  PublicSubnet0:
    Description: "SubnetId of public subnet 0"
    Value:
      Ref: "PublicSubnet0"
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-PublicSubnet0"

  InstanceId:
    Value: !Ref 'EC2Instance'
    Description: Instance Id of newly created instance

